controller_class: SimpleGreenGrassController
palete:
  dimension:
    rows: 5
    cols: 5
mode: scheduled
schedules:
  - initial_position:
      x: 1
      y: 2
    orientation: N 
    commands: "LMLMLMLMM"
  - initial_position:
      x: 3
      y: 3
    orientation: E
    commands: "MMRMMRMRRM"